"use client";

import { ArrowRight, Check, MonitorUp, RefreshCw, ShieldCheck, Timer, Users } from "lucide-react";
import Link from "next/link";
import { Logo } from "../../components/shared/Logo";
import { useClassroomState } from "../../components/shared/use-classroom-state";

export default function DemoPage() {
  const { state, reset, connection } = useClassroomState();
  return <main className="demo-page"><nav><Logo /><Link href="/">About Classroom Compass</Link></nav><section className="demo-hero"><span className="hero-kicker"><Timer size={15} />Reliable in under three minutes</span><h1>Comparing Decimals<br /><em>scripted demo</em></h1><p>One deterministic classroom moment. No cloud credentials, real student data, or retained media.</p><div className="demo-actions"><button data-testid="reset-demo" onClick={() => reset()}><RefreshCw />Reset all demo state</button><Link href="/teacher/session/session-demo">Enter teacher view<ArrowRight /></Link></div><small>{connection === "saved" ? "Local demo state ready" : "Preparing local state…"}</small></section><section className="demo-flow"><article className={state.demoStep !== "reset" ? "done" : "active"}><span>01</span><div><h2>Notice</h2><p>Play the fictional 0.35 vs 0.4 question from the teacher dashboard.</p></div><Check /></article><article className={["proposal", "bridge", "complete"].includes(state.demoStep) ? "done" : state.demoStep === "question" ? "active" : ""}><span>02</span><div><h2>Review</h2><p>Inspect the evidence and possible misconception; choose the teacher action.</p></div><Check /></article><article className={["bridge", "complete"].includes(state.demoStep) ? "done" : state.demoStep === "proposal" ? "active" : ""}><span>03</span><div><h2>Launch</h2><p>Open the public display and approve the hundred-grid bridge.</p></div><Check /></article><article className={state.demoStep === "complete" ? "done" : state.demoStep === "bridge" ? "active" : ""}><span>04</span><div><h2>Check & return</h2><p>Complete the interaction, then save only teacher-reviewed evidence.</p></div><Check /></article></section><section className="demo-cards"><article><MonitorUp /><h3>Public display</h3><p>Contains only the approved bridge and classroom-safe session context.</p><a href={`/display/${state.session.code}`} target="_blank">Open projector route<ArrowRight /></a></article><article><Users /><h3>Teacher workspace</h3><p>Private evidence, interpretation, participation, and privacy controls.</p><Link href="/teacher">Open dashboard<ArrowRight /></Link></article><article><ShieldCheck /><h3>Trust controls</h3><p>Pause, delete, export, retention, and explicit review are built into the flow.</p><Link href="/privacy">Read privacy guide<ArrowRight /></Link></article></section></main>;
}
