"use client";

import { Download, LockKeyhole, Pause, ShieldCheck, Trash2, VideoOff } from "lucide-react";
import { Logo } from "../../components/shared/Logo";
import { useClassroomState } from "../../components/shared/use-classroom-state";

export default function PrivacyPage() {
  const { state, update, reset } = useClassroomState();
  return <main className="info-page"><nav><Logo /><a href="/teacher">Back to teacher dashboard</a></nav><header><span className="hero-kicker"><ShieldCheck size={15} />For teachers and families</span><h1>Clear boundaries around classroom data.</h1><p>Classroom Compass is designed to help a teacher respond to a learning moment—not to watch, score, diagnose, or label a student.</p></header><section className="privacy-principles"><article><VideoOff /><h2>No raw media by default</h2><p>Camera and microphone streams are ephemeral. The prototype does not record or retain raw audio or video.</p></article><article><Pause /><h2>Teacher-controlled sensing</h2><p>Pause and end-session controls stop every active browser media track. Simulation remains clearly labeled.</p></article><article><LockKeyhole /><h2>Private stays private</h2><p>Student labels, histories, confidence bands, inferred struggles, and teacher notes are removed from the public display contract.</p></article></section><section className="data-control-panel"><div><span>Current fictional demo session</span><h2>{state.session.title}</h2><p>Retention applies to derived events and reviewed records, never raw media.</p></div><label>Derived-event retention<select value={state.session.retentionDays} onChange={(event) => update((current) => ({ ...current, session: { ...current.session, retentionDays: Number(event.target.value) as 0 | 7 | 30 } }))}><option value="0">Delete at session end</option><option value="7">7 days</option><option value="30">30 days</option></select></label><div className="data-buttons"><a href="/api/export"><Download />Export all session data</a><button onClick={() => reset()}><Trash2 />Delete and reset demo data</button></div></section><section className="do-not-list"><h2>What Classroom Compass does not do</h2><div>{["No facial recognition or biometric enrollment", "No emotion, attention, ability, honesty, disability, or learning-style inference", "No demographic inference from camera or voice", "No automatic grades, discipline, or high-stakes decisions", "No unrestricted browser or operating-system control", "No permanent student claim from a single model inference"].map((item) => <p key={item}><ShieldCheck />{item}</p>)}</div></section></main>;
}
